# Generated by Django 3.0.8 on 2020-08-02 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_auto_20200802_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='url',
            field=models.CharField(max_length=1000),
        ),
    ]
